@startuml
title user case of monopoly cards game

actor "player" as User

rectangle "user interface" {
    usecase "cards process" as F0
    usecase "draw cards" as F1
    usecase "use cards" as F2
    usecase "discard cards" as F3
    usecase "turn change" as F4

    usecase "behaviour" as F5
    usecase "pay" as F6
    usecase "settle" as F7
    usecase "trade" as F8
    usecase "objection" as F9
    usecase "fail" as F10
}

User --> F0
User --> F4
User --> F5

F0 ..> F1 : <<include>>
F0 ..> F2 : <<include>>
F0 ..> F3 : <<include>>

F5 ..> F6 : <<include>>
F5 ..> F7 : <<include>>
F5 ..> F8 : <<include>>
F5 ..> F9 : <<include>>
F5 ..> F10 : <<include>>


@enduml